(()=>{'use strict';
const canvas=document.getElementById('scene'),stage=document.getElementById('stage'),label=document.getElementById('status'),bubble=document.getElementById('bubble');
const gl=canvas.getContext('webgl',{antialias:true,alpha:true,preserveDrawingBuffer:false});
if(!gl){label.textContent='Ta przeglądarka nie obsługuje WebGL';return}
const vert=`attribute vec3 p;attribute vec3 n;uniform mat4 mvp;uniform mat4 world;varying vec3 normal;varying vec3 pos;void main(){vec4 w=world*vec4(p,1.);pos=w.xyz;normal=mat3(world)*n;gl_Position=mvp*vec4(p,1.);}`;
const frag=`precision mediump float;varying vec3 normal;varying vec3 pos;uniform vec3 color;uniform float glow;void main(){vec3 N=normalize(normal), L=normalize(vec3(-.5,1.2,1.7));float lit=.33+.67*max(dot(N,L),0.);float spec=pow(max(dot(reflect(-L,N),normalize(vec3(0.,.5,5.)-pos)),0.),22.);vec3 c=color*(glow>0.5?1.:lit)+vec3(spec*.28);if(glow>0.5)c+=color*.25;gl_FragColor=vec4(min(c,vec3(1.)),1.);}`;
function shader(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}
const prog=gl.createProgram();gl.attachShader(prog,shader(gl.VERTEX_SHADER,vert));gl.attachShader(prog,shader(gl.FRAGMENT_SHADER,frag));gl.linkProgram(prog);if(!gl.getProgramParameter(prog,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(prog));gl.useProgram(prog);const atP=gl.getAttribLocation(prog,'p'),atN=gl.getAttribLocation(prog,'n'),uMvp=gl.getUniformLocation(prog,'mvp'),uWorld=gl.getUniformLocation(prog,'world'),uCol=gl.getUniformLocation(prog,'color'),uGlow=gl.getUniformLocation(prog,'glow');
function makeMesh(verts,norms,inds){let p=gl.createBuffer(),n=gl.createBuffer(),i=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,p);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(verts),gl.STATIC_DRAW);gl.bindBuffer(gl.ARRAY_BUFFER,n);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(norms),gl.STATIC_DRAW);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,i);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(inds),gl.STATIC_DRAW);return{p,n,i,c:inds.length}}
function sphere(){const v=[],n=[],ix=[],R=18,C=28;for(let y=0;y<=R;y++){let phi=y*Math.PI/R;for(let x=0;x<=C;x++){let theta=x*2*Math.PI/C;let a=Math.sin(phi)*Math.cos(theta),b=Math.cos(phi),c=Math.sin(phi)*Math.sin(theta);v.push(a,b,c);n.push(a,b,c)}}for(let y=0;y<R;y++)for(let x=0;x<C;x++){const j=y*(C+1)+x;ix.push(j,j+C+1,j+1,j+1,j+C+1,j+C+2)}return makeMesh(v,n,ix)}
function cube(){const v=[],n=[],ix=[],faces=[[[0,0,1],[[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]]],[[0,0,-1],[[1,-1,-1],[-1,-1,-1],[-1,1,-1],[1,1,-1]]],[[1,0,0],[[1,-1,1],[1,-1,-1],[1,1,-1],[1,1,1]]],[[-1,0,0],[[-1,-1,-1],[-1,-1,1],[-1,1,1],[-1,1,-1]]],[[0,1,0],[[-1,1,1],[1,1,1],[1,1,-1],[-1,1,-1]]],[[0,-1,0],[[-1,-1,-1],[1,-1,-1],[1,-1,1],[-1,-1,1]]]];faces.forEach(([nn,vs],k)=>{vs.forEach(pt=>{v.push(...pt);n.push(...nn)});let j=k*4;ix.push(j,j+1,j+2,j,j+2,j+3)});return makeMesh(v,n,ix)}
const sph=sphere(),box=cube();
const mat=()=>[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];
function mul(a,b){let o=new Array(16).fill(0);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o}
function trans(x,y,z){let m=mat();m[12]=x;m[13]=y;m[14]=z;return m}
function scale(x,y,z){let m=mat();m[0]=x;m[5]=y;m[10]=z;return m}
function ry(a){let m=mat(),c=Math.cos(a),s=Math.sin(a);m[0]=c;m[8]=s;m[2]=-s;m[10]=c;return m}
function rz(a){let m=mat(),c=Math.cos(a),s=Math.sin(a);m[0]=c;m[4]=-s;m[1]=s;m[5]=c;return m}
function perspective(fov,aspect,near,far){const m=new Array(16).fill(0),f=1/Math.tan(fov/2);m[0]=f/aspect;m[5]=f;m[10]=(far+near)/(near-far);m[11]=-1;m[14]=2*far*near/(near-far);return m}
function lookAt(eye,target){let z=normalize(sub(eye,target)),x=normalize(cross([0,1,0],z)),y=cross(z,x);return[x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1]}
const sub=(a,b)=>a.map((v,i)=>v-b[i]),dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],normalize=v=>{let l=Math.hypot(...v)||1;return v.map(a=>a/l)};
const palette={white:[.91,.95,1],blue:[.035,.62,1],dark:[.04,.07,.12],black:[.018,.025,.04],side:[.12,.19,.28],orange:[1,.43,.055],screen:[.1,.53,.66],floor:[.92,.96,1],paper:[.97,.99,1],pink:[.92,.2,.33],sun:[1,.75,.16],green:[.2,.75,.54],gray:[.63,.72,.83]};
let projection,view,mode='tv',weather='rain',temperature=10,elapsed=0,last=0,modeStart=0,returnAt=0,greetText='',tvBroken=false,watchMs=0,lastTouch=0;
function draw(mesh,world,color,glow=0){const mv=mul(view,world),mvp=mul(projection,mv);gl.uniformMatrix4fv(uMvp,false,new Float32Array(mvp));gl.uniformMatrix4fv(uWorld,false,new Float32Array(world));gl.uniform3fv(uCol,palette[color]||color);gl.uniform1f(uGlow,glow);gl.bindBuffer(gl.ARRAY_BUFFER,mesh.p);gl.vertexAttribPointer(atP,3,gl.FLOAT,false,0,0);gl.enableVertexAttribArray(atP);gl.bindBuffer(gl.ARRAY_BUFFER,mesh.n);gl.vertexAttribPointer(atN,3,gl.FLOAT,false,0,0);gl.enableVertexAttribArray(atN);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,mesh.i);gl.drawElements(gl.TRIANGLES,mesh.c,gl.UNSIGNED_SHORT,0)}
function obj(mesh,parent,x,y,z,sx,sy,sz,color,glow=0,rot=0){let w=mul(parent,mul(trans(x,y,z),mul(ry(rot),scale(sx,sy,sz))));draw(mesh,w,color,glow)}
function robot(t){let cyc=(t-modeStart),isDrive=mode==='drive',isGreet=mode==='hello',isWork=mode==='work',isTV=mode==='tv';let x=isTV?-.90:isWork?-1.12:isGreet?-.65:-1.55+((cyc%9)/9)*2.7;let yaw=isTV?1.0:isWork?.5:isGreet?0:(Math.floor(cyc/9)%2? -1.3:1.3);let bob=Math.sin(t*4)*.035;let main=mul(trans(x,isDrive?bob:0,0),ry(yaw));if(isTV)main=mul(trans(x,-.16,0),ry(yaw));let head=mul(main,mul(trans(0,1.2+.07*Math.sin(t*1.65),0),ry(.10*Math.sin(t*1.1))));
obj(sph,main,0,.60,0,.42,.53,.37,'white');obj(sph,main,0,.62,.30,.12,.15,.09,'blue',1);
for(let side of [-1,1]){obj(sph,main,side*.46,.73,0,.15,.22,.18,'white');obj(sph,main,side*.47,.36,.02,.11,.24,.13,'side',0,.1*Math.sin(t*3+side));obj(sph,main,side*.28,.22,.01,.25,.24,.27,'white');obj(sph,main,side*.28,.12,.19,.17,.18,.14,'side');obj(sph,main,side*.28,.11,.34,.11,.12,.05,'blue',1)}
obj(sph,head,0,0,0,.62,.52,.48,'white');obj(sph,head,0,-.015,.39,.50,.40,.155,'black');for(let s of [-1,1]){obj(sph,head,s*.22,0,.53,.12,.15,.055,'blue',1);obj(sph,head,s*.24,0,.574,.055,.09,.018,'dark')}
obj(sph,head,-.60,0,0,.12,.20,.17,'side');obj(sph,head,.60,0,0,.12,.20,.17,'side');obj(sph,head,0,.58,0,.055,.22,.055,'side');obj(sph,head,0,.78,0,.115,.11,.115,'blue',1);
if(isWork){obj(box,main,.14,.53,.64,.45,.42,.04,'paper');for(let k=0;k<3;k++)obj(box,main,.14,.67-k*.10,.69,.31,.01,.01,'pink');obj(box,main,.46,.42,.70,.018,.32,.018,'blue',0,0.45+Math.sin(t*5)*.2)}
if(isGreet){obj(sph,main,.54,1.04,.05,.16,.19,.14,'white');obj(sph,main,.57,1.2,.05,.13,.11,.10,'side')}
}
function scenery(t){let I=mat();obj(box,I,0,-.29,0,5.1,.07,2.3,'floor');obj(sph,I,-.87,-.22,.1,.65,.06,.38,'gray');
obj(box,I,1.45,.45,-.18,.68,.63,.35,'orange');obj(box,I,1.40,.47,.19,.49,.41,.035,'dark');if(mode==='tv'&&!tvBroken){obj(box,I,1.40,.47,.235,.43,.34,.01,'screen',1);obj(box,I,1.43,.50,.25,.20,.12,.01, Math.sin(t*2)>0?'green':'sun',1)}else if(tvBroken){obj(box,I,1.40,.47,.235,.43,.34,.01,'gray');}else obj(box,I,1.40,.47,.235,.43,.34,.01,'black');obj(sph,I,1.93,.60,.18,.055,.06,.07,'dark');obj(sph,I,1.93,.37,.18,.055,.06,.07,'dark');obj(box,I,1.45,-.01,-.2,.55,.08,.30,'orange');
if(weather==='rain'&&mode==='hello'){obj(sph,I,-.65,2.3,.05,.55,.12,.32,'blue');obj(box,I,-.65,1.88,.05,.025,.55,.026,'dark')}if(weather==='sun'&&mode==='hello')obj(sph,I,-1.8,2.3,-.15,.22,.22,.12,'sun',1);
}
function resize(){const dpi=Math.min(devicePixelRatio||1,2),w=Math.max(1,canvas.clientWidth),h=Math.max(1,canvas.clientHeight);canvas.width=Math.round(w*dpi);canvas.height=Math.round(h*dpi);gl.viewport(0,0,canvas.width,canvas.height);projection=perspective(Math.PI/3,w/h,.1,100);view=lookAt([0,1.45,6.1],[0,.8,0])}
function setMode(m){mode=m;modeStart=elapsed;label.textContent={tv:'Ogląda telewizor — ekran jest włączony',drive:'Jeździ bokiem i obraca się',work:'Czyta i wypełnia CMR',hello:'Cześć! Co słychać?'}[m];bubble.classList.toggle('on',m==='hello');bubble.textContent=weather==='rain'?'Cześć! Dziś pada, około 10°C 🌧️':'Cześć! Dziś słonecznie, około 27°C ☀️';returnAt=m==='hello'?elapsed+6.5:0}
for(let [id,m] of Object.entries({tv:'tv',drive:'drive',cmr:'work',hello:'hello'}))document.getElementById(id).onclick=()=>setMode(m);
document.getElementById('rain').onclick=()=>{weather='rain';temperature=10;setMode('hello')};document.getElementById('sun').onclick=()=>{weather='sun';temperature=27;setMode('hello')};
const greet=()=>setMode('hello');canvas.addEventListener('pointerup',()=>{let now=performance.now();if(now-lastTouch<480)greet();lastTouch=now});canvas.addEventListener('dblclick',greet);
function frame(now){let dt=Math.min((now-last)/1000,.05);last=now;if(!document.hidden)elapsed+=dt;if(returnAt&&elapsed>returnAt){returnAt=0;setMode('tv')}if(mode==='tv'&&!document.hidden){watchMs+=dt;if(watchMs>30*60)tvBroken=true}const d=canvas.clientWidth/window.innerWidth;if(canvas.width===0||Math.abs(canvas.width-canvas.clientWidth*devicePixelRatio)>10)resize();gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);scenery(elapsed);robot(elapsed);requestAnimationFrame(frame)}
window.addEventListener('resize',resize);resize();setMode('tv');requestAnimationFrame(frame);
})();
